name: Build APK Bensalman
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download project ZIP
        run: |
          wget https://files.catbox.moe/kozr2w.zip -O project.zip
          unzip project.zip -d .
          # Trouve le dossier du projet
          PROJ=$(find . -name "pubspec.yaml" | head -n 1 | xargs dirname)
          echo "PROJ=$PROJ" >> $GITHUB_ENV
          mv $PROJ/* . || true
          mv $PROJ/.* . || true
          rm -rf project.zip __MACOSX
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Bensalman-Mesh-APK
          path: build/app/outputs/flutter-apk/app-release.apk
